### ISSUE TITLE
How the guests OS share the device?

### ISSUE THREAD

**Issue by wjhtinger** [bao-project/bao-hypervisor#14]
Such as, the Linux and freertos both write data to  the same uart, how to sync them? And, such as two guests OS want write EMMC，how?

**Comment by josecm** [comment]
Unfortunately, there is still no support in bao for sharing devices. We are starting to add VirtIO support to the hypervisor, but this is still WIP. The first backends should be available by Q1'22.

You should take a look at [icessspark's fork](https://github.com/icessspark/bao-hypervisor) where he started some work on this direction.

You could also do this in an ad hoc manner, by hosting the driver in one guest and using the inter-vm facilities to send work requests to other guest.
