### ISSUE TITLE
linux+freertos demo, how to know Linux run rightly?

### ISSUE THREAD

**Issue by wjhtinger** [bao-project/bao-hypervisor#15]
I use TX2 board.
I use TFTP in uboot to download bao.bin.  The uboot IP is set as below:
setenv  serverip 192.168.42.16
setenv  ipaddr 192.168.42.15

The UART log is：
tftp 0xa0000000 bao.bin;go 0xa0000000
## Starting application at 0xA0000000 ...
Bao Hypervisor
BAO WARNING: smmuv2 does not support coherent page table walks
Bao FreeRTOS guest
Task1: 0
Task2: 0
Task1: 1
Task2: 1
Task1: 2
Task2: 2
Task1: 3

So，it looks like that the FreeRTOS run OK. But I dont know if the Linux run OK too. In README.md, it said that Linux has the static IP(192.168.42.15), but I cant ping it sucessfully and cant ssh it too.
So ,what's wrong with Linux? How to debug?

**Comment by josecm** [comment]
I believe it would be hard to debug on TX2 without any king of external debugger. This was exactly my experience. I'd suggest changing the configuration to remove the freertos guest, while assigning the available uart to the Linux guest (also change the Linux guest device-tree to add the uart). Then having access to Linux through the serial console, try to investigate further why the ssh connection is not established.

**Comment by wjhtinger** [comment]
> I believe it would be hard to debug on TX2 without any kind of external debugger. This was exactly my experience. I'd suggest changing the configuration to remove the freertos guest, while assigning the available uart to the Linux guest (also change the Linux guest device-tree to add the uart). Then with access to Linux through the serial console, try to investigate further why the ssh connection is not established.
> 
> Also, are you using our branch of TF-A? This is needed to setup the correct stream ids so the the SMMU correctly translates DMA requests from the ethernet controller.

I check that the TX2 has two UART, right? So, do you know how to config anohter UART to Linux？

**Comment by josecm** [comment]
Any developments on this? If not, I will try to find some time to reproduce your issue.

**Comment by wjhtinger** [comment]
> Any developments on this? If not, I will try to find some time to reproduce your issue.

Not yet.

**Comment by josecm** [comment]
Were you able to solve this? If so, what was wrong and how? If not, are you still trying to solve this? In this case I'll try to reproduce  in the next couple of weeks, otherwise I'll close the issue.

**Comment by wjhtinger** [comment]
Sorry，these days I have some other work to do, no time to debug this problem any more. If you can have a look at it, appreciate it.
