### ISSUE TITLE
How to implement two-way communication between virtual machines?

### ISSUE THREAD

**Issue by Sunt-git** [bao-project/bao-hypervisor#26]
I ran it according to the demo, linux can actively communicate with freertos, but how does freertos actively communicate with linux?

**Comment by josecm** [comment]
The communication channel works the same in both direction. In the provided demos, we haven't written the Linux driver to enable and receive the interrupts, but this is essentially what's missing for Linux to receive asynchronous notifications from the FreeRTOS side.
