### ISSUE TITLE
Failed to alloc 

### ISSUE THREAD

**Issue by JianlongCao** [bao-project/bao-hypervisor#43]
Update the latest change in main branch, got following error:

> env
export CROSS_COMPILE=aarch64-none-elf-
export PLATFORM=qemu-aarch64-virt
export DEMO=linux+freertos

> launch
=> go 0x50000000
## Starting application at 0x50000000 ...
Bao Hypervisor
BAO INFO: parange_table[parange] = 40
BAO ERROR: Can't allocate address

I am trying to debug the problem, current find it will alloc 32768 pages,  and got failed at core/mmu/mem.c:397
Just let you know if you can reproduce at your side

**Comment by josecm** [comment]
@JianlongCao I've noted this issue a few days ago. I'll fix it in the next few days.

However, the bao-demos repo is not ready to run this latest modification, so I'd suggest keep using the old version with the demos until they are updated (until the end of the year this will probably be done)

**Comment by JianlongCao** [comment]
OK, please also check another 2 PR

**Comment by josecm** [comment]
Hey @JianlongCao. I believe this is working correctly now.
