### ISSUE TITLE
Is it possible to run ubuntu+freeRTOS？

### ISSUE THREAD

**Issue by wusnga8dn** [bao-project/bao-hypervisor#57]
Hello, your project is very interesting, I would like to ask, is it now possible to add support for the ubuntu system, can you run ubuntu+freeRTOS

**Comment by DavidMCerdeira** [comment]
We've never tested this specific use case, but in theory it should work. We have however successfully used android with Bao. As far as I know there should not be significant differences from the hypervisor point of view. 

What platform are you targeting?

**Comment by wusnga8dn** [comment]
Thanks for your reply. I am currently running bao-demo on Raspberry Pi 4b, but I have encountered some problems. At this stage, my target is Raspberry Pi 4b. Finally, my target platform is to run ubuntu+freeRTOS on Nvidia TX2 at the same time.

**Comment by DavidMCerdeira** [comment]
I'll add running ubuntu alongside freeRTOS to our backlog and we'll try it as soon as we can.
Regarding the issue you are having with the RPi4b demo I've noticed you have already submitted an issue in the bao-demo repository, so let's continue that part of the conversation there.

**Comment by wusnga8dn** [comment]
> I'll add running ubuntu alongside freeRTOS to our backlog and we'll try it as soon as we can. Regarding the issue you are having with the RPi4b demo I've noticed you have already submitted an issue in the bao-demo repository, so let's continue that part of the conversation there.

Hello, I am very much looking forward to the implementation of this particular example. If you have the latest progress, I really hope that you can let me know, and I will try it as soon as possible. Thank you so much for your work!

**Comment by josecm** [comment]
This will be implemented as a demo as soon as we get some spare cycles. This is marked as a feature request in [bao-demos](https://github.com/bao-project/bao-demos/issues/27).
