### ISSUE TITLE
Bitmap library throws error when compiled with optimizations level 2

### ISSUE THREAD

**Issue by ninolomata** [bao-project/bao-hypervisor#78]
There is an error when compiling Bao for RISC-V in `sbi_ipi_handler` function for gcc version 12.1.0

```
struct sbiret sbi_ipi_handler(unsigned long fid)
{
    if (fid != SBI_SEND_IPI_FID) return (struct sbiret){SBI_ERR_NOT_SUPPORTED};

    unsigned long hart_mask = vcpu_readreg(cpu()->vcpu, REG_A0);
    unsigned long hart_mask_base = vcpu_readreg(cpu()->vcpu, REG_A1);

    struct cpu_msg msg = {
        .handler = SBI_MSG_ID,
        .event = SEND_IPI,
    };

    for (size_t i = 0; i < sizeof(hart_mask) * 8; i++) {
        if (bitmap_get((bitmap_t*)&hart_mask, i)) {
            vcpuid_t vhart_id = hart_mask_base + i;
            cpuid_t phart_id = vm_translate_to_pcpuid(cpu()->vcpu->vm, vhart_id);
            if(phart_id != INVALID_CPUID) cpu_send_msg(phart_id, &msg);
        }
    }

    return (struct sbiret){SBI_SUCCESS};
}
```
The following error occurs:
```
In function 'bitmap_get',
    inlined from 'sbi_ipi_handler.part.0' at /media/ninolomata/Nino/bao-demos/wrkdir/srcs/bao/src/arch/riscv/sbi.c:260:13:
/media/ninolomata/Nino/bao-demos/wrkdir/srcs/bao/src/lib/inc/bitmap.h:43:16: error: 'hart_mask' is used uninitialized [-Werror=uninitialized]
   43 |     return (map[bit / BITMAP_GRANULE_LEN] & (ONE << (bit % BITMAP_GRANULE_LEN)))
      |             ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/media/ninolomata/Nino/bao-demos/wrkdir/srcs/bao/src/arch/riscv/sbi.c: In function 'sbi_ipi_handler.part.0':
/media/ninolomata/Nino/bao-demos/wrkdir/srcs/bao/src/arch/riscv/sbi.c:251:19: note: 'hart_mask' declared here
  251 |     unsigned long hart_mask = vcpu_readreg(cpu()->vcpu, REG_A0);
      |                   ^~~~~~~~~
cc1: all warnings being treated as errors
```
I  tested running Bao demos Linux + Freertos in the following scenarios:

- compile bao with optimization level 3 -> didn't compiled;
- compile bao with optimization level 0 and 1 -> compiled and demo worked; 
- switch the `bitmap_get` function to non inline function -> -> compiled and demo worked; 
- suppress the error -> -> compiled with warnings and demo worked;

**Comment by josecm** [comment]
Can you give for information on what exactly toolchain you are using and where to get it?

**Comment by josecm** [comment]
Anyways, I was able to reproduce this using `riscv64-unknown-elf-gcc (g2ee5e430018) 12.2.0` downloaded from [here](https://github.com/riscv-collab/riscv-gnu-toolchain/tags).

The solution here is quite straightforward. We need to use the `bit_get` function defined in *lib/inc/bit.h*. However, we should hunt for other possible issues related to casting integer types do bitmaps for extracting/manipulating bits and fix all in a single go.

**Comment by josecm** [comment]
@ninolomata Please check #79, it should solve the issue.

**Comment by ninolomata** [comment]
@josecm Just tested it is working.
